"""init

Revision ID: a8a60fcd0ed2
Revises: 
Create Date: 2026-05-30 22:46:52.161449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a8a60fcd0ed2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # GIN 트라이그램 인덱스에 필요한 extension
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_user',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('ticker_metadata',
    sa.Column('symbol', sa.String(length=30), nullable=False),
    sa.Column('name_kr', sa.String(length=100), nullable=False),
    sa.Column('name_en', sa.String(length=150), nullable=True),
    sa.Column('market', sa.Enum('KOSPI', 'KOSDAQ', 'NASDAQ', 'NYSE', 'AMEX', 'OTHER', name='market_type'), nullable=False),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('industry', sa.String(length=150), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('symbol')
    )
    op.create_index('idx_ticker_market_sector', 'ticker_metadata', ['market', 'sector'], unique=False)
    op.create_index('idx_ticker_name_en_trgm', 'ticker_metadata', [sa.text('name_en gin_trgm_ops')], unique=False, postgresql_using='gin')
    op.create_index('idx_ticker_name_kr', 'ticker_metadata', ['name_kr'], unique=False)
    op.create_index('idx_ticker_name_kr_trgm', 'ticker_metadata', [sa.text('name_kr gin_trgm_ops')], unique=False, postgresql_using='gin')
    op.create_table('data_refresh_job',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('symbol', sa.String(length=30), nullable=False),
    sa.Column('job_type', sa.Enum('PRICE', 'NEWS', 'FILING', 'FINANCIAL', 'TECHNICAL', 'EVENT', 'ALL', name='refresh_job_type'), server_default=sa.text("'ALL'::refresh_job_type"), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'PUBLISHED', 'RUNNING', 'COMPLETED', 'FAILED', 'SKIPPED', name='refresh_job_status'), server_default=sa.text("'QUEUED'::refresh_job_status"), nullable=False),
    sa.Column('kafka_topic', sa.String(length=100), nullable=True),
    sa.Column('kafka_key', sa.String(length=100), nullable=True),
    sa.Column('kafka_message_id', sa.String(length=100), nullable=True),
    sa.Column('kafka_partition', sa.Integer(), nullable=True),
    sa.Column('kafka_offset', sa.BIGINT(), nullable=True),
    sa.Column('priority', sa.Integer(), server_default=sa.text('100'), nullable=False),
    sa.Column('retry_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('max_retries', sa.Integer(), server_default=sa.text('3'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['symbol'], ['ticker_metadata.symbol'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_data_refresh_job_kafka_message_id', 'data_refresh_job', ['kafka_message_id'], unique=False)
    op.create_index('idx_data_refresh_job_status_schedule', 'data_refresh_job', ['status', 'scheduled_at'], unique=False)
    op.create_index('idx_data_refresh_job_symbol_type_status', 'data_refresh_job', ['symbol', 'job_type', 'status'], unique=False)
    op.create_index('idx_data_refresh_job_user_created', 'data_refresh_job', ['user_id', sa.text('created_at DESC')], unique=False)
    op.create_table('debate_session',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('symbol', sa.String(length=30), nullable=False),
    sa.Column('category', sa.Enum('technical', 'financial', 'market', 'macro', 'synthesis', name='debate_category'), nullable=False),
    sa.Column('mode', sa.Enum('moderator', name='debate_mode'), server_default=sa.text("'moderator'::debate_mode"), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'completed', 'failed', name='debate_status'), server_default=sa.text("'pending'::debate_status"), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cached_from_session_id', sa.UUID(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('cache_key', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['cached_from_session_id'], ['debate_session.id'], ),
    sa.ForeignKeyConstraint(['symbol'], ['ticker_metadata.symbol'], ),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_debate_cache_key', 'debate_session', ['cache_key'], unique=True, postgresql_where=sa.text('cache_key IS NOT NULL'))
    op.create_index('idx_debate_session_symbol', 'debate_session', ['symbol', 'category', sa.text('started_at DESC')], unique=False)
    op.create_index('idx_debate_session_user', 'debate_session', ['user_id', sa.text('started_at DESC')], unique=False)
    op.create_table('event_timeline',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('symbol', sa.String(length=30), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('event_title', sa.String(length=255), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('event_status', sa.String(length=30), nullable=False),
    sa.Column('source_type', sa.Enum('DART', 'NEWS', 'PRICE', 'FINANCIAL', 'TECHNICAL', 'INDUSTRY', 'MACRO', 'USER_INPUT', 'OTHER', name='source_type'), nullable=True),
    sa.Column('source_url', sa.String(length=2048), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['symbol'], ['ticker_metadata.symbol'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'event_date', 'event_title', name='uq_event_timeline')
    )
    op.create_index('idx_event_timeline_symbol_date', 'event_timeline', ['symbol', sa.text('event_date DESC')], unique=False)
    op.create_index('idx_event_timeline_type_status', 'event_timeline', ['event_type', 'event_status'], unique=False)
    op.create_table('filing_cache',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('symbol', sa.String(length=30), nullable=False),
    sa.Column('filing_title', sa.Text(), nullable=False),
    sa.Column('filing_type', sa.String(length=100), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('dart_receipt_no', sa.String(length=20), nullable=True),
    sa.Column('source_url', sa.String(length=2048), nullable=False),
    sa.Column('disclosed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ttl_until', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['symbol'], ['ticker_metadata.symbol'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dart_receipt_no')
    )
    op.create_index('idx_filing_symbol_disclosed', 'filing_cache', ['symbol', sa.text('disclosed_at DESC')], unique=False)
    op.create_index('idx_filing_ttl', 'filing_cache', ['symbol', 'ttl_until'], unique=False, postgresql_where=sa.text('ttl_until IS NOT NULL'))
    op.create_table('financial_cache',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('symbol', sa.String(length=30), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('fiscal_quarter', sa.Integer(), nullable=True),
    sa.Column('revenue', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('operating_profit', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('net_income', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('total_assets', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('total_liabilities', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('total_equity', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('per', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('pbr', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('roe', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('debt_ratio', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['symbol'], ['ticker_metadata.symbol'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'fiscal_year', 'fiscal_quarter', name='uq_financial_cache')
    )
    op.create_index('idx_financial_cache_lookup', 'financial_cache', ['symbol', sa.text('fiscal_year DESC'), 'fiscal_quarter'], unique=False)
    op.create_table('news_cache',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('symbol', sa.String(length=30), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('source_name', sa.String(length=150), nullable=True),
    sa.Column('source_url', sa.String(length=2048), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ttl_until', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['symbol'], ['ticker_metadata.symbol'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_news_source_url_unique', 'news_cache', ['source_url'], unique=True)
    op.create_index('idx_news_symbol_published', 'news_cache', ['symbol', sa.text('published_at DESC')], unique=False)
    op.create_index('idx_news_ttl', 'news_cache', ['symbol', 'ttl_until'], unique=False, postgresql_where=sa.text('ttl_until IS NOT NULL'))
    op.create_table('price_cache',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('symbol', sa.String(length=30), nullable=False),
    sa.Column('price_date', sa.Date(), nullable=False),
    sa.Column('open_price', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('high_price', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('low_price', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('close_price', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('adjusted_close', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('volume', sa.BIGINT(), nullable=True),
    sa.Column('change_rate', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['symbol'], ['ticker_metadata.symbol'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'price_date', name='uq_price_cache')
    )
    op.create_index('idx_price_cache_symbol_date', 'price_cache', ['symbol', sa.text('price_date DESC')], unique=False)
    op.create_table('technical_indicator_cache',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('symbol', sa.String(length=30), nullable=False),
    sa.Column('indicator_date', sa.Date(), nullable=False),
    sa.Column('ma20', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('ma60', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('ma120', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('rsi14', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('macd', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('macd_signal', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('macd_hist', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('volume_ma20', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['symbol'], ['ticker_metadata.symbol'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'indicator_date', name='uq_technical_indicator')
    )
    op.create_index('idx_technical_indicator_lookup', 'technical_indicator_cache', ['symbol', sa.text('indicator_date DESC')], unique=False)
    op.create_table('watchlist',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('symbol', sa.String(length=30), nullable=False),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['symbol'], ['ticker_metadata.symbol'], ),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'symbol', name='uq_watchlist')
    )
    op.create_index('idx_watchlist_symbol', 'watchlist', ['symbol'], unique=False)
    op.create_index('idx_watchlist_user', 'watchlist', ['user_id'], unique=False)
    op.create_table('agent_statement',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('round', sa.Enum('opening', 'rebuttal', 'closing', 'summary', name='debate_round'), nullable=False),
    sa.Column('round_order', sa.Integer(), nullable=False),
    sa.Column('agent_role', sa.Enum('bull', 'bear', 'moderator', 'system', name='agent_role'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['debate_session.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'round_order', name='uq_statement_order')
    )
    op.create_index('idx_statement_role', 'agent_statement', ['agent_role'], unique=False)
    op.create_index('idx_statement_session_order', 'agent_statement', ['session_id', 'round_order'], unique=False)
    op.create_table('debate_note',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('is_favorite', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('user_memo', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['debate_session.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'session_id', name='uq_debate_note')
    )
    op.create_table('moderator_summary',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('summary_content', sa.Text(), nullable=False),
    sa.Column('key_points', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['debate_session.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    op.create_table('evidence',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('statement_id', sa.UUID(), nullable=False),
    sa.Column('source_type', sa.Enum('DART', 'NEWS', 'PRICE', 'FINANCIAL', 'TECHNICAL', 'INDUSTRY', 'MACRO', 'USER_INPUT', 'OTHER', name='source_type'), nullable=False),
    sa.Column('source_url', sa.String(length=2048), nullable=True),
    sa.Column('source_label', sa.String(length=200), nullable=True),
    sa.Column('source_title', sa.Text(), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('excerpt', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('news_cache_id', sa.UUID(), nullable=True),
    sa.Column('filing_cache_id', sa.UUID(), nullable=True),
    sa.Column('price_cache_id', sa.UUID(), nullable=True),
    sa.Column('financial_cache_id', sa.UUID(), nullable=True),
    sa.Column('technical_indicator_cache_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['filing_cache_id'], ['filing_cache.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['financial_cache_id'], ['financial_cache.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['news_cache_id'], ['news_cache.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['price_cache_id'], ['price_cache.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['statement_id'], ['agent_statement.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['technical_indicator_cache_id'], ['technical_indicator_cache.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_evidence_source', 'evidence', ['source_type'], unique=False)
    op.create_index('idx_evidence_statement', 'evidence', ['statement_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_evidence_statement', table_name='evidence')
    op.drop_index('idx_evidence_source', table_name='evidence')
    op.drop_table('evidence')
    op.drop_table('moderator_summary')
    op.drop_table('debate_note')
    op.drop_index('idx_statement_session_order', table_name='agent_statement')
    op.drop_index('idx_statement_role', table_name='agent_statement')
    op.drop_table('agent_statement')
    op.drop_index('idx_watchlist_user', table_name='watchlist')
    op.drop_index('idx_watchlist_symbol', table_name='watchlist')
    op.drop_table('watchlist')
    op.drop_index('idx_technical_indicator_lookup', table_name='technical_indicator_cache')
    op.drop_table('technical_indicator_cache')
    op.drop_index('idx_price_cache_symbol_date', table_name='price_cache')
    op.drop_table('price_cache')
    op.drop_index('idx_news_ttl', table_name='news_cache', postgresql_where=sa.text('ttl_until IS NOT NULL'))
    op.drop_index('idx_news_symbol_published', table_name='news_cache')
    op.drop_index('idx_news_source_url_unique', table_name='news_cache')
    op.drop_table('news_cache')
    op.drop_index('idx_financial_cache_lookup', table_name='financial_cache')
    op.drop_table('financial_cache')
    op.drop_index('idx_filing_ttl', table_name='filing_cache', postgresql_where=sa.text('ttl_until IS NOT NULL'))
    op.drop_index('idx_filing_symbol_disclosed', table_name='filing_cache')
    op.drop_table('filing_cache')
    op.drop_index('idx_event_timeline_type_status', table_name='event_timeline')
    op.drop_index('idx_event_timeline_symbol_date', table_name='event_timeline')
    op.drop_table('event_timeline')
    op.drop_index('idx_debate_session_user', table_name='debate_session')
    op.drop_index('idx_debate_session_symbol', table_name='debate_session')
    op.drop_index('idx_debate_cache_key', table_name='debate_session', postgresql_where=sa.text('cache_key IS NOT NULL'))
    op.drop_table('debate_session')
    op.drop_index('idx_data_refresh_job_user_created', table_name='data_refresh_job')
    op.drop_index('idx_data_refresh_job_symbol_type_status', table_name='data_refresh_job')
    op.drop_index('idx_data_refresh_job_status_schedule', table_name='data_refresh_job')
    op.drop_index('idx_data_refresh_job_kafka_message_id', table_name='data_refresh_job')
    op.drop_table('data_refresh_job')
    op.drop_index('idx_ticker_name_kr_trgm', table_name='ticker_metadata', postgresql_using='gin')
    op.drop_index('idx_ticker_name_kr', table_name='ticker_metadata')
    op.drop_index('idx_ticker_name_en_trgm', table_name='ticker_metadata', postgresql_using='gin')
    op.drop_index('idx_ticker_market_sector', table_name='ticker_metadata')
    op.drop_table('ticker_metadata')
    op.drop_table('app_user')
    # ### end Alembic commands ###
